add multistep prod

diff --git a/.github/workflows/publish-study-definition.yml b/.github/workflows/publish-study-definition.yml
--- a/.github/workflows/publish-study-definition.yml
+++ b/.github/workflows/publish-study-definition.yml
@@ -63,20 +63,18 @@ jobs:
     environment: ${{ needs.determineenvironment.outputs.environment }}
     outputs:
       FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
+      FIREBASE_PROJECT_ID_PRODUCTION_US: ${{ vars.FIREBASE_PROJECT_ID_PRODUCTION_US }}
+      FIREBASE_PROJECT_ID_PRODUCTION_UK: ${{ vars.FIREBASE_PROJECT_ID_PRODUCTION_UK }}
     steps:
       - run: |
           echo "Injecting Environment Variables In Deployment Workflow: ${{ vars.FIREBASE_PROJECT_ID }}"
 
-  publish:
-    name: Build and Upload Study Bundle
+  build:
+    name: Build Study Bundle
     needs: [determineenvironment, vars]
     runs-on: macos-latest
     environment: ${{ needs.determineenvironment.outputs.environment }}
-    
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v4
-
     - name: Setup Xcode
       uses: maxim-lobanov/setup-xcode@v1
       with:
@@ -86,6 +84,10 @@ jobs:
       run: |
         swift run MHCStudyDefinitionExporterCLI export .
 
+  authenticate-and-publish:
+    name: Publish Study Bundle to Firebase Storage
+    if: needs.determineenvironment.outputs.environment != 'production'
+    needs: [build, determineenvironment, vars]
     - name: Setup Google Cloud SDK
       uses: google-github-actions/setup-gcloud@v2
 
@@ -109,7 +111,6 @@ jobs:
 
         gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
         gcloud config set project ${{ needs.vars.outputs.FIREBASE_PROJECT_ID }}
-
     - name: Upload study bundle to Firebase Storage
       run: |
         gsutil cp mhcStudyBundle.spezistudybundle.aar gs://${{ needs.vars.outputs.FIREBASE_PROJECT_ID }}.firebasestorage.app/public/
@@ -118,5 +119,73 @@ jobs:
 
     - name: Verify upload
       run: |
-        # List the files in the public directory to confirm upload
+        # List the files in the public directory to confirm
         gsutil ls gs://${{ needs.vars.outputs.FIREBASE_PROJECT_ID }}.firebasestorage.app/public/
+
+  authenticate-and-publish-production:
+    name: (Production) Publish Study Bundle to Firebase Storage
+    if: needs.determineenvironment.outputs.environment == 'production'
+    needs: [build, determineenvironment, vars]
+    - name: Setup Google Cloud SDK
+      uses: google-github-actions/setup-gcloud@v2
+
+    - name: (US production) Decode and authenticate to Google Cloud
+      run: |
+        if [ -z "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64_PRODUCTION_US }}" ]; then
+          echo "ERROR: GOOGLE_APPLICATION_CREDENTIALS_BASE64_PRODUCTION_US secret is not set"
+          exit 1
+        fi
+        if [ -z "${{ needs.vars.outputs.FIREBASE_PROJECT_ID_PRODUCTION_US }}" ]; then
+          echo "ERROR: FIREBASE_PROJECT_ID_PRODUCTION_US variable is not set"
+          exit 1
+        fi
+
+        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64_PRODUCTION_US }}" | base64 -d > /tmp/gcp-key.json
+
+        if [ ! -s /tmp/gcp-key.json ]; then
+          echo "ERROR: Failed to decode credentials or file is empty"
+          exit 1
+        fi
+
+        gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
+        gcloud config set project ${{ needs.vars.outputs.FIREBASE_PROJECT_ID_PRODUCTION_US }}
+    - name: (US production) Upload study bundle to Firebase Storage
+      run: |
+        gsutil cp mhcStudyBundle.spezistudybundle.aar gs://${{ needs.vars.outputs.FIREBASE_PROJECT_ID_PRODUCTION_US }}.firebasestorage.app/public/
+
+        gsutil acl ch -u AllUsers:R gs://${{ needs.vars.outputs.FIREBASE_PROJECT_ID_PRODUCTION_US }}.firebasestorage.app/public/mhcStudyBundle.spezistudybundle.aar
+
+    - name: (US production) Verify upload
+      run: |
+        # List the files in the public directory to confirm
+        gsutil ls gs://${{ needs.vars.outputs.FIREBASE_PROJECT_ID_PRODUCTION_US }}.firebasestorage.app/public/
+    - name: (UK production) Decode and authenticate to Google Cloud
+      run: |
+        if [ -z "${{ secrets.FIREBASE_PROJECT_ID_PRODUCTION_UK }}" ]; then
+          echo "ERROR: GOOGLE_APPLICATION_CREDENTIALS_BASE64_PRODUCTION_US secret is not set"
+          exit 1
+        fi
+        if [ -z "${{ needs.vars.outputs.FIREBASE_PROJECT_ID_PRODUCTION_UK }}" ]; then
+          echo "ERROR: FIREBASE_PROJECT_ID_PRODUCTION_US variable is not set"
+          exit 1
+        fi
+
+        echo "${{ secrets.FIREBASE_PROJECT_ID_PRODUCTION_UK }}" | base64 -d > /tmp/gcp-key.json
+
+        if [ ! -s /tmp/gcp-key.json ]; then
+          echo "ERROR: Failed to decode credentials or file is empty"
+          exit 1
+        fi
+
+        gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
+        gcloud config set project ${{ needs.vars.outputs.FIREBASE_PROJECT_ID_PRODUCTION_UK }}
+    - name: (UK production) Upload study bundle to Firebase Storage
+      run: |
+        gsutil cp mhcStudyBundle.spezistudybundle.aar gs://${{ needs.vars.outputs.FIREBASE_PROJECT_ID_PRODUCTION_UK }}.firebasestorage.app/public/
+
+        gsutil acl ch -u AllUsers:R gs://${{ needs.vars.outputs.FIREBASE_PROJECT_ID_PRODUCTION_UK }}.firebasestorage.app/public/mhcStudyBundle.spezistudybundle.aar
+
+    - name: (UK production) Verify upload
+      run: |
+        # List the files in the public directory to confirm
+        gsutil ls gs://${{ needs.vars.outputs.FIREBASE_PROJECT_ID_PRODUCTION_UK }}.firebasestorage.app/public/
